### PR TITLE
Retry download docker blob when connection dropped

### PR DESCRIPTION
**Pull request by hao-yu**
When syncing large docker repositories from a Red Hat registry (http://registry.redhat.io), the docker downloads will fail with connection reset by peer. This patch lets the docker plugin to retry the blob download when hitting the connection drop issue so that the task can be finished successfully.

closes #6471
https://pulp.plan.io/issues/6471

### CODE REVIEW

**Comment by hao-yu** [comment]
@ipanova Is this patch ok to proceed?

**Comment by ipanova** [comment]
@hao-yu Thank you for the PR. Pulp should not keep hitting on the server if the server dropped the connection. There is a ticket opened with IT to solve issue on the server side.

**Comment by hao-yu** [comment]
@ipanova just wondering is that any plan to reconsider this patch? Or Pulp team has other plan to fix the Jira issue?

**Comment by ipanova** [comment]
@hao-yu @midnightercz submitted a patch to nectar. It should solve the issue. Will you be able to help review and test it on the Satellite side?
@midnightercz can you please tag @hao-yu once you open the PR with the solved issues? https://github.com/pulp/nectar/pull/68/files

**Pull request closed without merging**
