### PR TITLE
Fix return value of upload_unit() to be consistent with plugin API

### PR DESCRIPTION
**Pull request by goosemania**
re #1747
https://pulp.plan.io/issues/1747

### CODE REVIEW

**Comment by rbarlow** [comment]
It seems like this should return False if the upload was not successful. What do you think?

**Comment by goosemania** [comment]
I agree with you completely.
But in your case if upload was not successful it will work that way : 
I will catch an exception here, fill the report with False value, then on platform inside try-expect I will check if the result is False->raise exception, then this exception again will be re-raised as a proper one %-\
I am really looking forward to re-think and re-design this as a part of new plugin API but for now I am trying to avoid these multiple try-excepts. Unsuccessful upload will be handled correctly anyway.
So if you think it is better to use report structure and not exception in case of unsuccessful upload, I will fix this plugin as well as the python one, iirc.

**Comment by rbarlow** [comment]
Hello @goosemania! I agree with you - the plugin API does not make much sense.

I think it probably does make sense to catch the exception here and return the sync report, but only because that is the documented behavior. It looks like the caller is just going to log and raise:

https://github.com/pulp/pulp/blob/2.8.1/server/pulp/server/managers/content/upload.py#L207-L222

So let's change this pull request to catch Exceptions and return a call report (which doesn't make sense) and we can refactor it with the plugin API rewrite later.

**Comment by goosemania** [comment]
@rbarlow, I've fixed this one and in pulp_python as well pulp/pulp_python#70

Re your comment, the caller raises nothing right now, but it should check the report and there is a PR pulp/pulp#2482 to fix that in a platform, which can be merged after all plugins will be fixed.

**Comment by rbarlow** [comment]
This looks great @goosemania, and let's keep this in mind to fix when we rework the plugin API. The plugin really should just let the Exception get raised and the platform should do the right thing. We'll get that right in the future. In the meantime, nice work!

**Comment by goosemania** [comment]
ok test

**Comment by dkliban** [comment]
Closing this PR. Opened a new PR against 2.0-dev branch

https://github.com/pulp/pulp_docker/pull/148

**Pull request closed without merging**
