### PR TITLE
Partial blobs not added during failed upload.

### PR DESCRIPTION
**Pull request by jortel**
https://pulp.plan.io/issues/3757

The `AddUnits` flow has been changed.  The `get_iterator()` returns an iterator for a _complete_ list of: `Manifest` and validated `Blobs` that are not already in the repository. As a result, an exception can be raised for missing of invalid blobs before anything is added in the DB.

The `process_main()` was doing too much and this was a good opportunity to refactor it.

I changed the import of `transport.Version` mainly to reduce ink.

### CODE REVIEW

**Comment by ipanova** [comment]
1. have a clean DB
2. create a repo
3. try to upload a partial tar with missing layer
4. upload will fail with expected message.
5. but there will be a traceback in the logs for finalize()
```
[ipanova@ina pulp_docker]$ pulp-admin docker repo create --repo-id 2
Warning: path should have mode 0700 because it may contain sensitive information: /home/ipanova/.pulp/

Repository [2] successfully created

[ipanova@ina pulp_docker]$ pulp-admin docker repo uploads upload  --repo-id 2 --file /home/ipanova/myprojects/tips/image-name-1.tar
Warning: path should have mode 0700 because it may contain sensitive information: /home/ipanova/.pulp/

+----------------------------------------------------------------------+
                              Unit Upload
+----------------------------------------------------------------------+

Extracting necessary metadata for each request...
[==================================================] 100%
Analyzing: image-name-1.tar
... completed

Creating upload requests on the server...
[==================================================] 100%
Initializing: image-name-1.tar
... completed

Starting upload of selected units. If this process is stopped through ctrl+c,
the uploads will be paused and may be resumed later using the resume command or
canceled entirely using the cancel command.

Uploading: image-name-1.tar
[==================================================] 100%
3696640/3696640 bytes
... completed

Importing into the repository...
This command may be exited via ctrl+c without affecting the request.


[\]
Running...

Task Failed

Layer 7cc9ff24526dfffdb8c188e6bae7e11d75d1ac5731d85e6fdccd5c7382d84207 is not
present in the image

Deleting the upload request...
... completed


Jun 19 19:02:30 ina pulp: pulp.plugins.util.publish_step:ERROR: [4c061dda] (31555-33920) Finalizing failed
Jun 19 19:02:30 ina pulp: pulp.plugins.util.publish_step:ERROR: [4c061dda] (31555-33920) Traceback (most recent call last):
Jun 19 19:02:30 ina pulp: pulp.plugins.util.publish_step:ERROR: [4c061dda] (31555-33920)   File "/home/ipanova/pulp_development/pulp/server/pulp/plugins/util/publish_step.py", line 264, in process
Jun 19 19:02:30 ina pulp: pulp.plugins.util.publish_step:ERROR: [4c061dda] (31555-33920)     self.finalize()
Jun 19 19:02:30 ina pulp: pulp.plugins.util.publish_step:ERROR: [4c061dda] (31555-33920)   File "/home/ipanova/pulp_development/pulp_docker/plugins/pulp_docker/plugins/importers/upload.py", line 506, in finalize
Jun 19 19:02:30 ina pulp: pulp.plugins.util.publish_step:ERROR: [4c061dda] (31555-33920)     item = item.__class__.objects.get(**item.unit_key)
Jun 19 19:02:30 ina pulp: pulp.plugins.util.publish_step:ERROR: [4c061dda] (31555-33920)   File "/usr/lib/python2.7/site-packages/mongoengine/queryset/base.py", line 242, in get
Jun 19 19:02:30 ina pulp: pulp.plugins.util.publish_step:ERROR: [4c061dda] (31555-33920)     raise queryset._document.DoesNotExist(msg)
Jun 19 19:02:30 ina pulp: pulp.plugins.util.publish_step:ERROR: [4c061dda] (31555-33920) DoesNotExist: Manifest matching query does not exist.
Jun 19 19:02:30 ina pulp: pulp.server.async.tasks:INFO: [4c061dda] Task failed : [4c061dda-777b-4686-acfb-ebb4c884b476] : Layer 7cc9ff24526dfffdb8c188e6bae7e11d75d1ac5731d85e6fdccd5c7382d84207 is not present in the image

```

**Comment by ipanova** [comment]
1. have a clean db
2. create repo 1 and upload image to it
3. create repo 2 and upload same image but partial one
4. upload will fail with expected message
5. manifest will be associated which is NOT expected
```
$ pulp-admin docker repo create --repo-id 1
Warning: path should have mode 0700 because it may contain sensitive information: /home/ipanova/.pulp/

Repository [1] successfully created

[ipanova@ina pulp_docker]$ pulp-admin docker repo uploads upload  --repo-id 1 --file /home/ipanova/myprojects/tips/image-name.tar
Warning: path should have mode 0700 because it may contain sensitive information: /home/ipanova/.pulp/

+----------------------------------------------------------------------+
                              Unit Upload
+----------------------------------------------------------------------+

Extracting necessary metadata for each request...
[==================================================] 100%
Analyzing: image-name.tar
... completed

Creating upload requests on the server...
[==================================================] 100%
Initializing: image-name.tar
... completed

Starting upload of selected units. If this process is stopped through ctrl+c,
the uploads will be paused and may be resumed later using the resume command or
canceled entirely using the cancel command.

Uploading: image-name.tar
[==================================================] 100%
3706880/3706880 bytes
... completed

Importing into the repository...
This command may be exited via ctrl+c without affecting the request.


[\]
Running...

Task Succeeded


Deleting the upload request...
... completed

[ipanova@ina pulp_docker]$ pulp-admin docker repo uploads upload  --repo-id 2 --file /home/ipanova/myprojects/tips/image-name-1.tar
Warning: path should have mode 0700 because it may contain sensitive information: /home/ipanova/.pulp/

+----------------------------------------------------------------------+
                              Unit Upload
+----------------------------------------------------------------------+

Extracting necessary metadata for each request...
[==================================================] 100%
Analyzing: image-name-1.tar
... completed

Creating upload requests on the server...
[==================================================] 100%
Initializing: image-name-1.tar
... completed

Starting upload of selected units. If this process is stopped through ctrl+c,
the uploads will be paused and may be resumed later using the resume command or
canceled entirely using the cancel command.

Uploading: image-name-1.tar
[==================================================] 100%
3696640/3696640 bytes
... completed

Importing into the repository...
This command may be exited via ctrl+c without affecting the request.


[\]
Running...

Task Failed

Layer 7cc9ff24526dfffdb8c188e6bae7e11d75d1ac5731d85e6fdccd5c7382d84207 is not
present in the image

Deleting the upload request...
... completed

[ipanova@ina pulp_docker]$ pulp-admin docker repo list
Warning: path should have mode 0700 because it may contain sensitive information: /home/ipanova/.pulp/

+----------------------------------------------------------------------+
                          Docker Repositories
+----------------------------------------------------------------------+

Id:                  2
Display Name:        None
Description:         None
Content Unit Counts: 
  Docker Manifest: 1

Id:                  1
Display Name:        None
Description:         None
Content Unit Counts: 
  Docker Blob:     6
  Docker Manifest: 1


```

**Comment by ipanova** [comment]
this is the reason why finalize fails:
https://github.com/jortel/pulp_docker/blob/45d8535458d0e11634532addfa9faf5847928782/plugins/pulp_docker/plugins/importers/upload.py#L493

```
for item in self.parent.available_units:
            if isinstance(item, models.Manifest):
                item = item.__class__.objects.get(**item.unit_key)
                self.parent.uploaded_unit = item
```

`available_units` are NOT the one which are saved in pulp but the one which we identified from the json file in tar https://github.com/jortel/pulp_docker/blob/45d8535458d0e11634532addfa9faf5847928782/plugins/pulp_docker/plugins/importers/upload.py#L245

**Comment by ipanova** [comment]
the manifest gets associated because we call GetLocalUnitsStep() which makes the association in case it finds units in pulp. Why just the manifests gets associated and  the blobs are ignored i still have not discovered. In any case we cannot make this associations because of this statement https://pulp.plan.io/issues/3497#note-12
https://github.com/jortel/pulp_docker/blob/45d8535458d0e11634532addfa9faf5847928782/plugins/pulp_docker/plugins/importers/upload.py#L113
https://github.com/pulp/pulp/blob/2-master/server/pulp/plugins/util/publish_step.py#L1257

Probably by just removing this step would solve the issue

**Comment by jortel** [comment]
Thanks for the review, @ipanova.  I agree with your findings and recommended resolution.  Have pushed the requested changes.

**Pull request merged**
